DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
	name VARCHAR(55) NOT NULL,
	registration VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS course;
CREATE TABLE IF NOT EXISTS course(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
	name VARCHAR(55) NOT NULL,
	description VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS student_course;
CREATE TABLE student_course(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
	student_id INT NOT NULL,
	course_id INT NOT NULL,

	FOREIGN KEY (student_id) REFERENCES student (id),
	FOREIGN KEY (course_id) REFERENCES course (id)
);